version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ~/mosquitto/config:/mosquitto/config
      - ~/mosquitto/data:/mosquitto/data
      - ~/mosquitto/log:/mosquitto/log
    ports:
      - "80:80"
    restart: always